import React from 'react';
import { PageHeader } from '../../components/ui/PageHeader';
import { CTASection } from '../../components/ui/CTASection';
import { Badge } from '../../components/ui/Badge';
import { StatCounter } from '../../components/ui/StatCounter';
import { BarChart3, PieChart, TrendingUp, AlertTriangle, ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';

export const KeyNumbers: React.FC = () => {
  return (
    <div>
      <PageHeader
        badge="QUANTITATIVE EVIDENCE BASE"
        title="Key Numbers &amp; Empirical Data"
        intro="Our research findings anchor on concrete measurements gathered across 600+ campus student surveys, 32 hours of physical mess hall observations, and systematic tray-waste audits."
        breadcrumbs={[
          { label: 'Research', href: '/research/field-observations' },
          { label: 'Key Numbers & Data' },
        ]}
      />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-12">
        {/* The 4 Core Headline Metrics */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <StatCounter
            target={50}
            suffix="%"
            label="Energy Mismatch"
            subtext="Variance between daily caloric expenditure and static canteen food served."
            highlight={true}
          />
          <StatCounter
            target={70}
            prefix="60–"
            suffix="%"
            label="Plate Food Waste"
            subtext="Proportion of daily mess waste volume generated by unfinished plates."
            highlight={false}
          />
          <StatCounter
            target={600}
            suffix="+"
            label="Students Surveyed"
            subtext="Comprehensive campus survey across engineering, science, and arts wings."
            highlight={false}
          />
          <StatCounter
            target={10}
            prefix="< "
            suffix="s"
            label="Serving Latency"
            subtext="Total end-to-end time to generate scoop recommendations at the counter."
            highlight={true}
          />
        </div>

        {/* Breakdown 1: The 50% Energy Mismatch Quantified */}
        <div className="bg-white rounded-3xl p-6 sm:p-8 border border-stone-200 shadow-sm space-y-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between pb-4 border-b border-stone-100 gap-2">
            <div>
              <Badge variant="mint">ENERGY EXPENDITURE DYNAMICS</Badge>
              <h3 className="text-xl sm:text-2xl font-bold text-stone-900 mt-2">
                The 50% Energy Mismatch: Sedentary vs. Athletic Days
              </h3>
            </div>
            <span className="text-xs font-mono font-bold text-stone-500 bg-stone-50 p-2 rounded-lg border border-stone-200">
              Sample: 68kg Student (175cm, 20yo)
            </span>
          </div>

          <p className="text-sm text-stone-700 leading-relaxed">
            The chart below contrasts physiological caloric needs with the static mess portion. While a student's actual caloric requirements oscillate between <strong>1,970 kcal</strong> (exam revision day) and <strong>2,950 kcal</strong> (inter-hostel football training), the traditional mess serves a fixed <strong>2,400 kcal</strong> allocation every single day.
          </p>

          {/* Visual comparison bars */}
          <div className="space-y-4 pt-2">
            <div>
              <div className="flex justify-between text-xs font-bold text-stone-800 mb-1">
                <span>Low Activity (Exam Prep / Desk Bound) — Actual Need:</span>
                <span className="text-amber-700 font-mono">1,970 kcal (SURPLUS +430 kcal)</span>
              </div>
              <div className="w-full bg-stone-100 rounded-full h-4 overflow-hidden flex">
                <div className="bg-amber-400 h-full rounded-full" style={{ width: '66%' }} />
              </div>
              <span className="text-[11px] text-stone-500 mt-0.5 block">Result: 430 kcal surplus dumped into waste bin or stored as sluggish visceral fat</span>
            </div>

            <div>
              <div className="flex justify-between text-xs font-bold text-stone-800 mb-1">
                <span>Default Fixed Mess Serving Plate (Static Every Day):</span>
                <span className="text-stone-700 font-mono">2,400 kcal (DEFAULT)</span>
              </div>
              <div className="w-full bg-stone-100 rounded-full h-4 overflow-hidden flex">
                <div className="bg-stone-500 h-full rounded-full" style={{ width: '80%' }} />
              </div>
              <span className="text-[11px] text-stone-500 mt-0.5 block">Standard serving size: 2 cups rice, 3 rotis, 1 cup dal, 1 cup sabzi</span>
            </div>

            <div>
              <div className="flex justify-between text-xs font-bold text-stone-800 mb-1">
                <span>High Activity (Varsity Practice / Gym Conditioning) — Actual Need:</span>
                <span className="text-emerald-700 font-mono">2,950 kcal (DEFICIT -550 kcal)</span>
              </div>
              <div className="w-full bg-stone-100 rounded-full h-4 overflow-hidden flex">
                <div className="bg-[#1F6F4B] h-full rounded-full" style={{ width: '100%' }} />
              </div>
              <span className="text-[11px] text-stone-500 mt-0.5 block">Result: 550 kcal deficit forces athlete to seek junk food snacks or suffer muscle catabolism</span>
            </div>
          </div>
        </div>

        {/* Breakdown 2: What Ends Up in the Food Waste Bins? */}
        <div className="bg-white rounded-3xl p-6 sm:p-8 border border-stone-200 shadow-sm space-y-6">
          <div className="border-b border-stone-100 pb-4">
            <Badge variant="amber">TRAY AUDIT DATA</Badge>
            <h3 className="text-xl sm:text-2xl font-bold text-stone-900 mt-2">
              Composition of 60–70% Daily Plate Waste
            </h3>
            <p className="text-xs text-stone-500 mt-1">
              Data compiled from 14-day weighing audits at Hostel Dining Hall A clearing station.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div className="p-4 rounded-2xl bg-amber-50 border border-amber-200 text-center">
              <span className="text-3xl font-black text-amber-800 font-mono">48%</span>
              <h4 className="text-xs font-bold text-stone-900 uppercase tracking-wider mt-1">Cooked Rice</h4>
              <p className="text-[11px] text-stone-600 mt-1">Single largest dumped item due to excessive default scoops</p>
            </div>

            <div className="p-4 rounded-2xl bg-amber-50 border border-amber-200 text-center">
              <span className="text-3xl font-black text-amber-800 font-mono">24%</span>
              <h4 className="text-xs font-bold text-stone-900 uppercase tracking-wider mt-1">Rotis / Chapatis</h4>
              <p className="text-[11px] text-stone-600 mt-1">Students take 3-4 by habit and abandon the final 1.5 rotis</p>
            </div>

            <div className="p-4 rounded-2xl bg-stone-50 border border-stone-200 text-center">
              <span className="text-3xl font-black text-stone-800 font-mono">18%</span>
              <h4 className="text-xs font-bold text-stone-900 uppercase tracking-wider mt-1">Gravy / Dal Scrapings</h4>
              <p className="text-[11px] text-stone-600 mt-1">Excess watery curry mixed with uneaten grains</p>
            </div>

            <div className="p-4 rounded-2xl bg-stone-50 border border-stone-200 text-center">
              <span className="text-3xl font-black text-stone-800 font-mono">10%</span>
              <h4 className="text-xs font-bold text-stone-900 uppercase tracking-wider mt-1">Cooked Vegetables</h4>
              <p className="text-[11px] text-stone-600 mt-1">Sabzi discarded due to taste or satiety threshold</p>
            </div>
          </div>
        </div>

        {/* Cross navigation */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <Link
            to="/research/survey-methodology"
            className="bg-[#FAFAF7] hover:bg-white p-5 rounded-2xl border border-stone-200 hover:border-[#1F6F4B] transition-all flex items-center justify-between group"
          >
            <div>
              <span className="text-xs font-bold text-[#1F6F4B] uppercase">Methodology</span>
              <h4 className="text-base font-bold text-stone-900">How 600+ Students Were Surveyed</h4>
            </div>
            <ArrowRight className="w-5 h-5 text-stone-400 group-hover:text-[#1F6F4B] group-hover:translate-x-1 transition-all" />
          </Link>

          <Link
            to="/research/survey-results"
            className="bg-[#FAFAF7] hover:bg-white p-5 rounded-2xl border border-stone-200 hover:border-[#1F6F4B] transition-all flex items-center justify-between group"
          >
            <div>
              <span className="text-xs font-bold text-[#1F6F4B] uppercase">Survey Data</span>
              <h4 className="text-base font-bold text-stone-900">Survey Results Deep Dive</h4>
            </div>
            <ArrowRight className="w-5 h-5 text-stone-400 group-hover:text-[#1F6F4B] group-hover:translate-x-1 transition-all" />
          </Link>
        </div>
      </div>

      <CTASection
        title="Put These Numbers to the Test"
        description="Try our interactive calculator and see how your personal metrics align with the research data."
        primaryLink={{ text: 'Try Portion Recommender', href: '/tools/portion-recommender' }}
        secondaryLink={{ text: 'View Solution Architecture', href: '/solution/overview' }}
      />
    </div>
  );
};
