import React from 'react';
import { PageHeader } from '../../components/ui/PageHeader';
import { CTASection } from '../../components/ui/CTASection';
import { Badge } from '../../components/ui/Badge';
import { BeforeAfterDiagram } from '../../components/diagrams/BeforeAfterDiagram';
import { ArrowRight, Check, X, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';

export const Comparison: React.FC = () => {
  const comparisonRows = [
    {
      dimension: 'Portion Determination',
      before: 'Habit, visual impulse, or whatever the server ladles onto the stainless steel plate.',
      after: 'Scientific Mifflin-St Jeor BMR + discrete daily activity multiplier (1.2x to 1.9x).',
    },
    {
      dimension: 'Daily Plate Waste',
      before: '60–70% of waste volume generated by discarded half-eaten rice mounds and rotis.',
      after: 'Projected 40–55% drop in plate scrapings via calibrated scoop requests.',
    },
    {
      dimension: 'Energy Balance Alignment',
      before: 'Up to 50% energy mismatch between low-activity study days and varsity training.',
      after: 'Near-zero caloric variance; portions adapt immediately to morning training logs.',
    },
    {
      dimension: 'Counter Queue Latency',
      before: 'Irregular delays caused by students arguing over extra rotis or slow indecision.',
      after: 'Streamlined < 10s counter pass; staff glance at digital scoop badges instantly.',
    },
    {
      dimension: 'Afternoon Brain Fog',
      before: '76% of diners report severe post-lunch sluggishness during 2:00 PM labs.',
      after: 'Controlled glycemic load and balanced macronutrients eliminate post-prandial crashes.',
    },
    {
      dimension: 'Kitchen Procurement',
      before: 'Cooks guess headcounts; massive surplus cooked rice dumped into organic waste bins.',
      after: 'Aggregate daily student activity logs allow kitchen staff to optimize prep batches.',
    },
  ];

  return (
    <div>
      <PageHeader
        badge="TRANSFORMATION BENCHMARK"
        title="Before vs. After: What Changes in the Mess"
        intro="A side-by-side comparative analysis detailing how introducing personalized portion guidance transforms the daily dining hall experience for students, staff, and hostel management."
        breadcrumbs={[
          { label: 'Solution', href: '/solution/overview' },
          { label: 'Before vs. After Comparison' },
        ]}
      />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-12">
        {/* Visual Before/After Diagram */}
        <BeforeAfterDiagram />

        {/* Granular Comparison Table */}
        <div className="bg-white rounded-3xl p-6 sm:p-8 border border-stone-200 shadow-sm space-y-6">
          <div className="border-b border-stone-100 pb-4">
            <Badge variant="mint">OPERATIONAL MATRIX</Badge>
            <h3 className="text-xl sm:text-2xl font-bold text-stone-900 mt-2">
              Granular Operational Impact Across 6 Dimensions
            </h3>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse min-w-[650px]">
              <thead>
                <tr className="border-b border-stone-200 text-xs font-bold text-stone-500 uppercase tracking-wider">
                  <th className="py-3 px-4 w-1/4">Operational Dimension</th>
                  <th className="py-3 px-4 w-3/8 text-red-700 bg-red-50/50 rounded-t-xl">
                    Before: Traditional Mess Status Quo
                  </th>
                  <th className="py-3 px-4 w-3/8 text-[#1F6F4B] bg-emerald-50/50 rounded-t-xl">
                    After: Smart Meal &amp; Activity Assistant
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-stone-200 text-xs sm:text-sm">
                {comparisonRows.map((row, idx) => (
                  <tr key={idx} className="hover:bg-stone-50/50 transition-colors">
                    <td className="py-4 px-4 font-bold text-stone-900 align-top">
                      {row.dimension}
                    </td>
                    <td className="py-4 px-4 bg-red-50/20 text-stone-700 align-top">
                      <div className="flex items-start space-x-2">
                        <X className="w-4 h-4 text-red-500 shrink-0 mt-0.5" />
                        <span>{row.before}</span>
                      </div>
                    </td>
                    <td className="py-4 px-4 bg-emerald-50/20 font-medium text-stone-900 align-top">
                      <div className="flex items-start space-x-2">
                        <Check className="w-4 h-4 text-[#1F6F4B] shrink-0 mt-0.5 font-bold" />
                        <span>{row.after}</span>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Cross navigation */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <Link
            to="/solution/future-roadmap"
            className="bg-[#FAFAF7] hover:bg-white p-5 rounded-2xl border border-stone-200 hover:border-[#1F6F4B] transition-all flex items-center justify-between group"
          >
            <div>
              <span className="text-xs font-bold text-[#1F6F4B] uppercase">Future Roadmap</span>
              <h4 className="text-base font-bold text-stone-900">What Lies Beyond: Wearables &amp; Smart Scales</h4>
            </div>
            <ArrowRight className="w-5 h-5 text-stone-400 group-hover:text-[#1F6F4B] group-hover:translate-x-1 transition-all" />
          </Link>

          <Link
            to="/solution/limitations"
            className="bg-[#FAFAF7] hover:bg-white p-5 rounded-2xl border border-stone-200 hover:border-[#1F6F4B] transition-all flex items-center justify-between group"
          >
            <div>
              <span className="text-xs font-bold text-[#1F6F4B] uppercase">Scientific Transparency</span>
              <h4 className="text-base font-bold text-stone-900">Honest Limitations &amp; Edge Cases</h4>
            </div>
            <ArrowRight className="w-5 h-5 text-stone-400 group-hover:text-[#1F6F4B] group-hover:translate-x-1 transition-all" />
          </Link>
        </div>
      </div>

      <CTASection
        title="Experience This Transformation in Real Time"
        description="Try the interactive tool that delivers these exact operational improvements."
        primaryLink={{ text: 'Try Live Portion Recommender', href: '/tools/portion-recommender' }}
        secondaryLink={{ text: 'Join 4-Week Pilot Cohort', href: '/get-involved' }}
      />
    </div>
  );
};
